setwd("C:/Users/linds/OneDrive/Documents/R")
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip", "C:/Users/linds/OneDrive/Documents/R/household.zip")
ZipFile<-"C:/Users/linds/OneDrive/Documents/R/household.zip"
unzip(ZipFile,exdir = "./house")
txtFile <- "C:/Users/linds/OneDrive/Documents/R/house/household_power_consumption.txt"
household<-read.table(txtFile, header = T, sep = ";", na.strings="?")
Feb2007<- subset(household, Date == "2/2/2007" | Date == "1/2/2007")
times<- strptime(paste(Feb2007$Date, Feb2007$Time, sep=" "),"%d/%m/%Y %H:%M:%S")
png("plot3.png", width = 480, height = 480, units = "px")
plot(times, Feb2007$Sub_metering_1, type = "n",xlab = "", ylab="Energy sub metering")
lines(times, Feb2007$Sub_metering_1, col = "black")
lines(times, Feb2007$Sub_metering_2, col = "red")
lines(times, Feb2007$Sub_metering_3, col = "blue")
legend("topright",legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black", "red", "blue"), lty = "solid")
dev.off()